### ISSUE TITLE
FATL [config] only support fake-ip dns mode(dns.enhanced-mode)

### ISSUE THREAD

**Issue by deepdream** [TPClash/tpclash#11]
debain10-slim

-------------------
root@debian10:/home/tjm# ./tpclash-mihomo-linux-amd64 -c config.yaml

████████╗██████╗  ██████╗██╗      █████╗ ███████╗██╗  ██╗
╚══██╔══╝██╔══██╗██╔════╝██║     ██╔══██╗██╔════╝██║  ██║
   ██║   ██████╔╝██║     ██║     ███████║███████╗███████║
   ██║   ██╔═══╝ ██║     ██║     ██╔══██║╚════██║██╔══██║
   ██║   ██║     ╚██████╗███████╗██║  ██║███████║██║  ██║
   ╚═╝   ╚═╝      ╚═════╝╚══════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝

Version: v0.2.1
Build: 2024-02-02 15:52:37
Clash Core: Mihomo v1.18.0
Commit: 5a4955145c03e2f03eb3a15591fea29438f559c5

2024-02-02 17:19:03 INFO [main] starting tpclash...
2024-02-02 17:19:03 INFO [helper/sysctl] enable net.ipv4.ip_forward...
2024-02-02 17:19:03 INFO [helper/sysctl] enable net.ipv4.conf.all.route_localnet                                                                                                                                                             ...
2024-02-02 17:19:03 INFO [static] creating storage dir...
2024-02-02 17:19:03 INFO [static] copy static files...
2024-02-02 17:19:03 FATL [config] only support fake-ip dns mode(dns.enhanced-mod                                                                                                                                                             e)

**Comment by j33h22** [comment]
Dear [deepdream](https://github.com/deepdream)

  I am sorry for that. 
  Due to the implementation principle of TPClash, TPClash only support TUN and fake-ip.
  If you want to use fake-ip,you can change the dns configuration in your config file,like this:

```yaml
dns:
  enable: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  # use-hosts: true # lookup hosts and return IP record
  # Hostnames in this list will not be resolved with fake IPs
  # i.e. questions to these domain names will always be answered with their
  # real IP addresses
  fake-ip-filter:
    - '*.lan'
    - '*.local'
  # These nameservers are used to resolve the DNS nameserver hostnames below.
  # Specify IP addresses only
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  # Supports UDP, TCP, DoT, DoH. You can specify the port to connect to.
  # All DNS questions are sent directly to the nameserver, without proxies
  # involved. Clash answers the DNS question with the first result gathered.
  nameserver:
    {{range $index, $server := DefaultDNS}}- {{$server}}
    {{end}}
```

  Then it should run normally.

  Hope you can continue support this project.

Best regards,
Ju33Huang22
